# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectCharacterWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_characterWindow(object):
    def setupUi(self, characterWindow):
        characterWindow.setObjectName(_fromUtf8("characterWindow"))
        characterWindow.resize(928, 525)
        self.frame = QtGui.QFrame(characterWindow)
        self.frame.setGeometry(QtCore.QRect(0, 20, 901, 491))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.btn_1 = QtGui.QPushButton(self.frame)
        self.btn_1.setGeometry(QtCore.QRect(40, 80, 81, 81))
        self.btn_1.setText(_fromUtf8(""))
        self.btn_1.setObjectName(_fromUtf8("btn_1"))
        self.btn_2 = QtGui.QPushButton(self.frame)
        self.btn_2.setGeometry(QtCore.QRect(130, 80, 81, 81))
        self.btn_2.setText(_fromUtf8(""))
        self.btn_2.setObjectName(_fromUtf8("btn_2"))
        self.btn_3 = QtGui.QPushButton(self.frame)
        self.btn_3.setGeometry(QtCore.QRect(220, 80, 81, 81))
        self.btn_3.setText(_fromUtf8(""))
        self.btn_3.setObjectName(_fromUtf8("btn_3"))
        self.btn_5 = QtGui.QPushButton(self.frame)
        self.btn_5.setGeometry(QtCore.QRect(40, 170, 81, 81))
        self.btn_5.setText(_fromUtf8(""))
        self.btn_5.setObjectName(_fromUtf8("btn_5"))
        self.btn_6 = QtGui.QPushButton(self.frame)
        self.btn_6.setGeometry(QtCore.QRect(130, 170, 81, 81))
        self.btn_6.setText(_fromUtf8(""))
        self.btn_6.setObjectName(_fromUtf8("btn_6"))
        self.btn_7 = QtGui.QPushButton(self.frame)
        self.btn_7.setGeometry(QtCore.QRect(220, 170, 81, 81))
        self.btn_7.setText(_fromUtf8(""))
        self.btn_7.setObjectName(_fromUtf8("btn_7"))
        self.btn_8 = QtGui.QPushButton(self.frame)
        self.btn_8.setGeometry(QtCore.QRect(310, 170, 81, 81))
        self.btn_8.setText(_fromUtf8(""))
        self.btn_8.setObjectName(_fromUtf8("btn_8"))
        self.btn_9 = QtGui.QPushButton(self.frame)
        self.btn_9.setGeometry(QtCore.QRect(400, 170, 81, 81))
        self.btn_9.setText(_fromUtf8(""))
        self.btn_9.setObjectName(_fromUtf8("btn_9"))
        self.btn_10 = QtGui.QPushButton(self.frame)
        self.btn_10.setGeometry(QtCore.QRect(400, 260, 81, 81))
        self.btn_10.setText(_fromUtf8(""))
        self.btn_10.setObjectName(_fromUtf8("btn_10"))
        self.btn_11 = QtGui.QPushButton(self.frame)
        self.btn_11.setGeometry(QtCore.QRect(310, 350, 81, 81))
        self.btn_11.setText(_fromUtf8(""))
        self.btn_11.setObjectName(_fromUtf8("btn_11"))
        self.btn_12 = QtGui.QPushButton(self.frame)
        self.btn_12.setGeometry(QtCore.QRect(220, 350, 81, 81))
        self.btn_12.setText(_fromUtf8(""))
        self.btn_12.setObjectName(_fromUtf8("btn_12"))
        self.btn_13 = QtGui.QPushButton(self.frame)
        self.btn_13.setGeometry(QtCore.QRect(310, 260, 81, 81))
        self.btn_13.setText(_fromUtf8(""))
        self.btn_13.setObjectName(_fromUtf8("btn_13"))
        self.btn_14 = QtGui.QPushButton(self.frame)
        self.btn_14.setGeometry(QtCore.QRect(220, 260, 81, 81))
        self.btn_14.setText(_fromUtf8(""))
        self.btn_14.setObjectName(_fromUtf8("btn_14"))
        self.btn_15 = QtGui.QPushButton(self.frame)
        self.btn_15.setGeometry(QtCore.QRect(40, 260, 81, 81))
        self.btn_15.setText(_fromUtf8(""))
        self.btn_15.setObjectName(_fromUtf8("btn_15"))
        self.btn_16 = QtGui.QPushButton(self.frame)
        self.btn_16.setGeometry(QtCore.QRect(130, 260, 81, 81))
        self.btn_16.setText(_fromUtf8(""))
        self.btn_16.setObjectName(_fromUtf8("btn_16"))
        self.btn_17 = QtGui.QPushButton(self.frame)
        self.btn_17.setGeometry(QtCore.QRect(130, 350, 81, 81))
        self.btn_17.setText(_fromUtf8(""))
        self.btn_17.setObjectName(_fromUtf8("btn_17"))
        self.btn_18 = QtGui.QPushButton(self.frame)
        self.btn_18.setGeometry(QtCore.QRect(40, 350, 81, 81))
        self.btn_18.setText(_fromUtf8(""))
        self.btn_18.setObjectName(_fromUtf8("btn_18"))
        self.btn_21 = QtGui.QPushButton(self.frame)
        self.btn_21.setGeometry(QtCore.QRect(490, 80, 81, 81))
        self.btn_21.setText(_fromUtf8(""))
        self.btn_21.setObjectName(_fromUtf8("btn_21"))
        self.btn_22 = QtGui.QPushButton(self.frame)
        self.btn_22.setGeometry(QtCore.QRect(490, 350, 81, 81))
        self.btn_22.setText(_fromUtf8(""))
        self.btn_22.setObjectName(_fromUtf8("btn_22"))
        self.btn_23 = QtGui.QPushButton(self.frame)
        self.btn_23.setGeometry(QtCore.QRect(490, 260, 81, 81))
        self.btn_23.setText(_fromUtf8(""))
        self.btn_23.setObjectName(_fromUtf8("btn_23"))
        self.btn_24 = QtGui.QPushButton(self.frame)
        self.btn_24.setGeometry(QtCore.QRect(400, 350, 81, 81))
        self.btn_24.setText(_fromUtf8(""))
        self.btn_24.setObjectName(_fromUtf8("btn_24"))
        self.btn_25 = QtGui.QPushButton(self.frame)
        self.btn_25.setGeometry(QtCore.QRect(490, 170, 81, 81))
        self.btn_25.setText(_fromUtf8(""))
        self.btn_25.setObjectName(_fromUtf8("btn_25"))
        self.btn_26 = QtGui.QPushButton(self.frame)
        self.btn_26.setGeometry(QtCore.QRect(400, 80, 81, 81))
        self.btn_26.setText(_fromUtf8(""))
        self.btn_26.setObjectName(_fromUtf8("btn_26"))
        self.btn_20 = QtGui.QPushButton(self.frame)
        self.btn_20.setGeometry(QtCore.QRect(580, 170, 81, 81))
        self.btn_20.setText(_fromUtf8(""))
        self.btn_20.setObjectName(_fromUtf8("btn_20"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 10, 611, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.name_l = QtGui.QLabel(self.frame)
        self.name_l.setGeometry(QtCore.QRect(690, 100, 41, 31))
        self.name_l.setObjectName(_fromUtf8("name_l"))
        self.pswd_l = QtGui.QLabel(self.frame)
        self.pswd_l.setGeometry(QtCore.QRect(690, 310, 51, 21))
        self.pswd_l.setObjectName(_fromUtf8("pswd_l"))
        self.next_btn = QtGui.QPushButton(self.frame)
        self.next_btn.setGeometry(QtCore.QRect(800, 440, 61, 31))
        self.next_btn.setObjectName(_fromUtf8("next_btn"))
        self.btn_19 = QtGui.QPushButton(self.frame)
        self.btn_19.setGeometry(QtCore.QRect(580, 80, 81, 81))
        self.btn_19.setText(_fromUtf8(""))
        self.btn_19.setObjectName(_fromUtf8("btn_19"))
        self.btn_4 = QtGui.QPushButton(self.frame)
        self.btn_4.setGeometry(QtCore.QRect(310, 80, 81, 81))
        self.btn_4.setText(_fromUtf8(""))
        self.btn_4.setObjectName(_fromUtf8("btn_4"))
        self.password_label = QtGui.QLabel(self.frame)
        self.password_label.setGeometry(QtCore.QRect(750, 310, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setText(_fromUtf8(""))
        self.password_label.setObjectName(_fromUtf8("password_label"))
        self.name_label = QtGui.QLabel(self.frame)
        self.name_label.setGeometry(QtCore.QRect(730, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.name_label.setFont(font)
        self.name_label.setText(_fromUtf8(""))
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(730, 140, 151, 151))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(_fromUtf8("Background:rgb(255, 255, 255)"))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton.raise_()
        self.btn_1.raise_()
        self.btn_2.raise_()
        self.btn_3.raise_()
        self.btn_5.raise_()
        self.btn_6.raise_()
        self.btn_7.raise_()
        self.btn_8.raise_()
        self.btn_9.raise_()
        self.btn_10.raise_()
        self.btn_11.raise_()
        self.btn_12.raise_()
        self.btn_13.raise_()
        self.btn_14.raise_()
        self.btn_15.raise_()
        self.btn_16.raise_()
        self.btn_17.raise_()
        self.btn_18.raise_()
        self.btn_21.raise_()
        self.btn_22.raise_()
        self.btn_23.raise_()
        self.btn_24.raise_()
        self.btn_25.raise_()
        self.btn_26.raise_()
        self.btn_20.raise_()
        self.label.raise_()
        self.name_l.raise_()
        self.pswd_l.raise_()
        self.next_btn.raise_()
        self.btn_19.raise_()
        self.btn_4.raise_()
        self.password_label.raise_()
        self.name_label.raise_()

        self.retranslateUi(characterWindow)
        QtCore.QMetaObject.connectSlotsByName(characterWindow)

    def retranslateUi(self, characterWindow):
        characterWindow.setWindowTitle(_translate("characterWindow", "Select your character", None))
        self.label.setText(_translate("characterWindow", "Select your character!  Someone easy to remember for you. Maybe a special movie character from your childhood, or your favortie player from this list. You can see how the password would start below the picture.", None))
        self.name_l.setText(_translate("characterWindow", "Name: ", None))
        self.pswd_l.setText(_translate("characterWindow", "Password: ", None))
        self.next_btn.setText(_translate("characterWindow", "Next", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    characterWindow = QtGui.QWidget()
    ui = Ui_characterWindow()
    ui.setupUi(characterWindow)
    characterWindow.show()
    sys.exit(app.exec_())

